version: '3.8'

services:
  energymeter:
    container_name: energymeter
    image: slothcroissant/rpi-energymeter:nightly
    environment:
      - ct0=20
      - ct1=20
      - ct2=20
      - ct3=20
      - ct4=20
      - ct5=20
      - ct6=20
      - ct7=30
      - db_host=dbhost.lan
      - db_port=3306
      - db_database=data
      - db_table=energymeter
      - db_user=dbuser
      - db_pass=dbpassword
    devices:
      - /dev/spidev0.0
