name: Docker Image CI

on:
  push:
    branches: [ nightly ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: slothcroissant
      DOCKER_CONTAINER_NAME: rpi-powermeter
      DOCKER_TARGET_PLATFORM: linux/arm/v7

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Prepare
      if: success()
      id: prepare
      run: |
        echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}
        echo ::set-output name=tag::$(date +%Y.%m.%d-$GITHUB_RUN_NUMBER)

    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: "${DOCKER_USERNAME}"
        password: ${{ secrets.DOCKER_PASSWORD }} 

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: "${DOCKER_USERNAME}"
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: ${{ steps.prepare.outputs.docker_platform }}
        push: true
        tags: |
          ${DOCKER_USERNAME}/${DOCKER_CONTAINER_NAME}:${{ steps.prepare.outputs.tag }}
          ${DOCKER_USERNAME}/${DOCKER_CONTAINER_NAME}:nightly
          ghcr.io/${DOCKER_USERNAME}/${DOCKER_CONTAINER_NAME}:${{ steps.prepare.outputs.tag }}
          ghcr.io/${DOCKER_USERNAME}/${DOCKER_CONTAINER_NAME}:nightly
          